/* automatically generated by rust-bindgen 0.65.1 */

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(clippy::missing_safety_doc)]

#[link(name = "game_performance.z")]
unsafe extern "C" {}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GamePerformance_DeviceInfo {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GamePerformance_GpuInfo {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GamePerformance_CpuInfo {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GamePerformance_ThermalInfo {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GamePerformance_ThermalInfoQueryParameters {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GamePerformance_InitParameters {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GamePerformance_PackageInfo {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GamePerformance_ConfigInfo {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GamePerformance_SceneInfo {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GamePerformance_NetInfo {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GamePerformance_PlayerInfo {
    _unused: [u8; 0],
}
#[doc = " UNITY"]
pub const GamePerformance_EngineType_GAME_PERFORMANCE_ENGINE_TYPE_UNITY:
    GamePerformance_EngineType = 1;
#[doc = " UNREAL"]
pub const GamePerformance_EngineType_GAME_PERFORMANCE_ENGINE_TYPE_UNREAL:
    GamePerformance_EngineType = 2;
#[doc = " MESSIAH"]
pub const GamePerformance_EngineType_GAME_PERFORMANCE_ENGINE_TYPE_MESSIAH:
    GamePerformance_EngineType = 3;
#[doc = " COCOS"]
pub const GamePerformance_EngineType_GAME_PERFORMANCE_ENGINE_TYPE_COCOS:
    GamePerformance_EngineType = 4;
#[doc = " Other engine type"]
pub const GamePerformance_EngineType_GAME_PERFORMANCE_ENGINE_TYPE_OTHERS:
    GamePerformance_EngineType = 200;
#[doc = " @brief Defines engine information.\n @since 5.0.2(14)"]
pub type GamePerformance_EngineType = u32;
#[doc = " MOBA"]
pub const GamePerformance_GameType_GAME_PERFORMANCE_GAME_TYPE_MOBA: GamePerformance_GameType = 1;
#[doc = " RPG"]
pub const GamePerformance_GameType_GAME_PERFORMANCE_GAME_TYPE_RPG: GamePerformance_GameType = 2;
#[doc = " FPS"]
pub const GamePerformance_GameType_GAME_PERFORMANCE_GAME_TYPE_FPS: GamePerformance_GameType = 3;
#[doc = " FTG"]
pub const GamePerformance_GameType_GAME_PERFORMANCE_GAME_TYPE_FTG: GamePerformance_GameType = 4;
#[doc = " RAC"]
pub const GamePerformance_GameType_GAME_PERFORMANCE_GAME_TYPE_RAC: GamePerformance_GameType = 5;
#[doc = " Other game type"]
pub const GamePerformance_GameType_GAME_PERFORMANCE_GAME_TYPE_OTHERS: GamePerformance_GameType =
    200;
#[doc = " @brief Defines game type.\n @since 5.0.2(14)"]
pub type GamePerformance_GameType = u32;
#[doc = " SMOOTH (Low Quality)"]
pub const GamePerformance_PictureQualityLevel_GAME_PERFORMANCE_PQL_SMOOTH:
    GamePerformance_PictureQualityLevel = 1;
#[doc = " BALANCED (Medium Quality)"]
pub const GamePerformance_PictureQualityLevel_GAME_PERFORMANCE_PQL_BALANCED:
    GamePerformance_PictureQualityLevel = 2;
#[doc = " HD (High Definition)"]
pub const GamePerformance_PictureQualityLevel_GAME_PERFORMANCE_PQL_HD:
    GamePerformance_PictureQualityLevel = 3;
#[doc = " HDR (High Dynamic Range)"]
pub const GamePerformance_PictureQualityLevel_GAME_PERFORMANCE_PQL_HDR:
    GamePerformance_PictureQualityLevel = 4;
#[doc = " UHD (Ultra High Definition)"]
pub const GamePerformance_PictureQualityLevel_GAME_PERFORMANCE_PQL_UHD:
    GamePerformance_PictureQualityLevel = 5;
#[doc = " @brief Defines level of picture quality.\n @since 5.0.2(14)"]
pub type GamePerformance_PictureQualityLevel = u32;
#[doc = " Level 1."]
pub const GamePerformance_SceneImportanceLevel_GAME_PERFORMANCE_SIL_LEVEL1:
    GamePerformance_SceneImportanceLevel = 1;
#[doc = " Level 2."]
pub const GamePerformance_SceneImportanceLevel_GAME_PERFORMANCE_SIL_LEVEL2:
    GamePerformance_SceneImportanceLevel = 2;
#[doc = " Level 3."]
pub const GamePerformance_SceneImportanceLevel_GAME_PERFORMANCE_SIL_LEVEL3:
    GamePerformance_SceneImportanceLevel = 3;
#[doc = " Level 4."]
pub const GamePerformance_SceneImportanceLevel_GAME_PERFORMANCE_SIL_LEVEL4:
    GamePerformance_SceneImportanceLevel = 4;
#[doc = " Level 5."]
pub const GamePerformance_SceneImportanceLevel_GAME_PERFORMANCE_SIL_LEVEL5:
    GamePerformance_SceneImportanceLevel = 5;
#[doc = " @brief Defines importance level of scene.\n @since 5.0.2(14)"]
pub type GamePerformance_SceneImportanceLevel = u32;
#[doc = " Low."]
pub const GamePerformance_CpuLevel_GAME_PERFORMANCE_CPU_LEVEL_LOW: GamePerformance_CpuLevel = 1;
#[doc = " Middle."]
pub const GamePerformance_CpuLevel_GAME_PERFORMANCE_CPU_LEVEL_MIDDLE: GamePerformance_CpuLevel = 2;
#[doc = " High."]
pub const GamePerformance_CpuLevel_GAME_PERFORMANCE_CPU_LEVEL_HIGH: GamePerformance_CpuLevel = 3;
#[doc = " @brief Defines level of CPU.\n @since 5.0.2(14)"]
pub type GamePerformance_CpuLevel = u32;
#[doc = " Low."]
pub const GamePerformance_GpuLevel_GAME_PERFORMANCE_GPU_LEVEL_LOW: GamePerformance_GpuLevel = 1;
#[doc = " Middle."]
pub const GamePerformance_GpuLevel_GAME_PERFORMANCE_GPU_LEVEL_MIDDLE: GamePerformance_GpuLevel = 2;
#[doc = " High."]
pub const GamePerformance_GpuLevel_GAME_PERFORMANCE_GPU_LEVEL_HIGH: GamePerformance_GpuLevel = 3;
#[doc = " @brief Defines level of GPU.\n @since 5.0.2(14)"]
pub type GamePerformance_GpuLevel = u32;
#[doc = " Low."]
pub const GamePerformance_DdrLevel_GAME_PERFORMANCE_DDR_LEVEL_LOW: GamePerformance_DdrLevel = 1;
#[doc = " Middle."]
pub const GamePerformance_DdrLevel_GAME_PERFORMANCE_DDR_LEVEL_MIDDLE: GamePerformance_DdrLevel = 2;
#[doc = " High."]
pub const GamePerformance_DdrLevel_GAME_PERFORMANCE_DDR_LEVEL_HIGH: GamePerformance_DdrLevel = 3;
#[doc = " @brief Defines level of DDR.\n @since 5.0.2(14)"]
pub type GamePerformance_DdrLevel = u32;
#[doc = " Light load."]
pub const GamePerformance_NetLoad_GAME_PERFORMANCE_NET_LOAD_LIGHT: GamePerformance_NetLoad = 1;
#[doc = " Moderate load."]
pub const GamePerformance_NetLoad_GAME_PERFORMANCE_NET_LOAD_MODERATE: GamePerformance_NetLoad = 2;
#[doc = " Heavy load."]
pub const GamePerformance_NetLoad_GAME_PERFORMANCE_NET_LOAD_HEAVY: GamePerformance_NetLoad = 3;
#[doc = " @brief Defines level of net load.\n @since 5.0.2(14)"]
pub type GamePerformance_NetLoad = u32;
#[doc = " Success."]
pub const GamePerformance_ErrorCode_GAME_PERFORMANCE_SUCCESS: GamePerformance_ErrorCode = 0;
#[doc = " Invalid parameter."]
pub const GamePerformance_ErrorCode_GAME_PERFORMANCE_PARAM_INVALID: GamePerformance_ErrorCode = 401;
#[doc = " System internal error."]
pub const GamePerformance_ErrorCode_GAME_PERFORMANCE_INTERNAL_ERROR: GamePerformance_ErrorCode =
    1010300001;
#[doc = " Invalid caller."]
pub const GamePerformance_ErrorCode_GAME_PERFORMANCE_AUTH_FAILED: GamePerformance_ErrorCode =
    1010300002;
#[doc = " Invalid request."]
pub const GamePerformance_ErrorCode_GAME_PERFORMANCE_INVALID_REQUEST: GamePerformance_ErrorCode =
    1010300003;
#[doc = " Parameter error."]
pub const GamePerformance_ErrorCode_GAME_PERFORMANCE_PARAM_ERROR: GamePerformance_ErrorCode =
    1010300004;
#[doc = " @brief Defines ErrorCode.\n @since 5.0.2(14)"]
pub type GamePerformance_ErrorCode = u32;
#[doc = " @brief THERMAL.\n @since 5.0.2(14)"]
pub const GamePerformance_DeviceInfoType_GAME_PERFORMANCE_DEVICEINFO_TYPE_THERMAL:
    GamePerformance_DeviceInfoType = 0;
#[doc = " @brief GPU.\n @since 5.0.2(14)"]
pub const GamePerformance_DeviceInfoType_GAME_PERFORMANCE_DEVICEINFO_TYPE_GPU:
    GamePerformance_DeviceInfoType = 1;
#[doc = " @brief CPU.\n @since 6.0.2(22)"]
pub const GamePerformance_DeviceInfoType_GAME_PERFORMANCE_DEVICEINFO_TYPE_CPU:
    GamePerformance_DeviceInfoType = 2;
#[doc = " @brief Defines type of deviceInfo.\n @since 5.0.2(14)"]
pub type GamePerformance_DeviceInfoType = u32;
#[doc = " @brief The callback signature which is used in {@link HMS_GamePerformance_RegisterThermalLevelChangedCallback}.\n the function will be invoked once when thermal level changed and thermal level is less than 3.\n the function will be invoked once evenry ten seconds when thermal level is greater than or equal level 3.\n\n @param deviceInfo Output data. Detail information of device {@link GamePerformance_DeviceInfo}.\n @param userData User specific data.\n @since 5.0.2(14)"]
pub type GamePerformance_ThermalLevelChangedCallback = ::std::option::Option<
    unsafe extern "C" fn(
        deviceInfo: *mut GamePerformance_DeviceInfo,
        userData: *mut ::std::os::raw::c_void,
    ),
>;
unsafe extern "C" {
    #[doc = " @brief Create {@link GamePerformance_InitParameters} instance , which is used in {@link HMS_GamePerformance_Init}.\n\n @param initParameters Output data. {@link GamePerformance_InitParameters} instance.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_CreateInitParameters(
        initParameters: *mut *mut GamePerformance_InitParameters,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Destroy {@link GamePerformance_InitParameters} instance, When the instance is no longer needed.\n\n @param initParameters Secondary pointer to the {@link GamePerformance_InitParameters} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_DestroyInitParameters(
        initParameters: *mut *mut GamePerformance_InitParameters,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set bundle name for {@link GamePerformance_InitParameters} instance.\n\n @param initParameters Pointer to the {@link GamePerformance_InitParameters} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param bundleName The bundleName of the app.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_InitParameters_SetBundleName(
        initParameters: *mut GamePerformance_InitParameters,
        bundleName: *const ::std::os::raw::c_char,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set app version for {@link GamePerformance_InitParameters} instance.\n\n @param initParameters Pointer to the {@link GamePerformance_InitParameters} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param appVersion The version of the app.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_InitParameters_SetAppVersion(
        initParameters: *mut GamePerformance_InitParameters,
        appVersion: *const ::std::os::raw::c_char,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " Init game performance with {@link GamePerformance_InitParameters} instance.\n\n @param initParameters Pointer to the {@link GamePerformance_InitParameters} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n         {@link GAME_PERFORMANCE_INTERNAL_ERROR} 1010300001 - System internal error.\n         {@link GAME_PERFORMANCE_AUTH_FAILED} 1010300002 - Invalid caller.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_Init(
        initParameters: *mut GamePerformance_InitParameters,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Destroy {@link GamePerformance_CpuInfo} instance, When the instance is no longer needed.\n\n @param cpuInfo Secondary pointer to the {@link GamePerformance_CpuInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_ERROR} 1010300004 - Parameter error. Parameter should't be nullptr.\n @since 6.0.2(22)"]
    pub fn HMS_GamePerformance_DestroyCpuInfo(
        cpuInfo: *mut *mut GamePerformance_CpuInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Query CPU info.\n\n @param cpuInfo Output data. {@link GamePerformance_CpuInfo} instance.\n When the CPU info is no longer needed, it must be released using {@link HMS_GamePerformance_DestroyCpuInfo}.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_INTERNAL_ERROR} 1010300001 - System internal error.\n                                                              Please submit this issue via the online ticket system.\n         {@link GAME_PERFORMANCE_INVALID_REQUEST} 1010300003 - Invalid request.\n                                                             {@link HMS_GamePerformance_Init} should be called first.\n         {@link GAME_PERFORMANCE_PARAM_ERROR} 1010300004 - Parameter error. Parameter should't be nullptr.\n @since 6.0.2(22)"]
    pub fn HMS_GamePerformance_QueryCpuInfo(
        cpuInfo: *mut *mut GamePerformance_CpuInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Get CPU info {@link GamePerformance_CpuInfo} from device info {@link GamePerformance_DeviceInfo}.\n\n @param deviceInfo Pointer to the {@link GamePerformance_DeviceInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param cpuInfo Output data. Secondary pointer to the {@link GamePerformance_CpuInfo} instance.\n When the CPU info is no longer needed, it must be released using {@link HMS_GamePerformance_DestroyCpuInfo}.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_ERROR} 1010300004 - Parameter error. Parameter should't be nullptr.\n @since 6.0.2(22)"]
    pub fn HMS_GamePerformance_DeviceInfo_GetCpuInfo(
        deviceInfo: *mut GamePerformance_DeviceInfo,
        cpuInfo: *mut *mut GamePerformance_CpuInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Get CPU load level from CPU info {@link GamePerformance_CpuInfo}.\n\n @param cpuInfo Pointer to the {@link GamePerformance_CpuInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param cpuLoadLevel Output data. CPU load level of the previous ten frames,\n the value ranges from 1 to 10 in ascending order.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_ERROR} 1010300004 - Parameter error. Parameter should't be nullptr.\n @since 6.0.2(22)"]
    pub fn HMS_GamePerformance_CpuInfo_GetCpuLoadLevel(
        cpuInfo: *mut GamePerformance_CpuInfo,
        cpuLoadLevel: *mut i32,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Get single thread CPU load level from CPU info {@link GamePerformance_CpuInfo}.\n\n @param cpuInfo Pointer to the {@link GamePerformance_CpuInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param singleThreadLoadLevel Output data. Single thread CPU load level of the previous ten frames,\n the value ranges from 1 to 10 in ascending order.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_ERROR} 1010300004 - Parameter error. Parameter should't be nullptr.\n @since 6.0.2(22)"]
    pub fn HMS_GamePerformance_CpuInfo_GetSingleThreadLoadLevel(
        cpuInfo: *mut GamePerformance_CpuInfo,
        singleThreadLoadLevel: *mut i32,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Get recommend normalized current from thermal info {@link GamePerformance_ThermalInfo}.\n\n @param thermalInfo Pointer to the {@link GamePerformance_ThermalInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param recommendCurrent Output data. Recommend normalized current.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_ERROR} 1010300004 - Parameter error. Parameter should't be nullptr.\n @since 6.0.2(22)"]
    pub fn HMS_GamePerformance_ThermalInfo_GetRecommendNormalizedCurrent(
        thermalInfo: *mut GamePerformance_ThermalInfo,
        recommendCurrent: *mut i32,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Get normalized current of now from thermal info {@link GamePerformance_ThermalInfo}.\n\n @param thermalInfo Pointer to the {@link GamePerformance_ThermalInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param nowCurrent Output data. Normalized current of now.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_ERROR} 1010300004 - Parameter error. Parameter should't be nullptr.\n @since 6.0.2(22)"]
    pub fn HMS_GamePerformance_ThermalInfo_GetNowNormalizedCurrent(
        thermalInfo: *mut GamePerformance_ThermalInfo,
        nowCurrent: *mut i32,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Get recommend max normalized current from thermal info {@link GamePerformance_ThermalInfo}.\n\n @param thermalInfo Pointer to the {@link GamePerformance_ThermalInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param recommendMaxCurrent Output data. Recommend max normalized current.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_ERROR} 1010300004 - Parameter error. Parameter should't be nullptr.\n @since 6.0.2(22)"]
    pub fn HMS_GamePerformance_ThermalInfo_GetRecommendMaxNormalizedCurrent(
        thermalInfo: *mut GamePerformance_ThermalInfo,
        recommendMaxCurrent: *mut i32,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Create {@link GamePerformance_PackageInfo} instance,\n which is used in {@link HMS_GamePerformance_UpdatePackageInfo}.\n\n @param packageInfo Output data. {@link GamePerformance_PackageInfo} instance.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_CreatePackageInfo(
        packageInfo: *mut *mut GamePerformance_PackageInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Destroy {@link GamePerformance_PackageInfo} instance, When the instance is no longer needed.\n\n @param packageInfo Secondary pointer to the {@link GamePerformance_PackageInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_DestroyPackageInfo(
        packageInfo: *mut *mut GamePerformance_PackageInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set bundle name for {@link GamePerformance_PackageInfo} instance.\n\n @param packageInfo Pointer to the {@link GamePerformance_PackageInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param bundleName The bundleName of the app.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_PackageInfo_SetBundleName(
        packageInfo: *mut GamePerformance_PackageInfo,
        bundleName: *const ::std::os::raw::c_char,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set app version for {@link GamePerformance_PackageInfo} instance.\n\n @param packageInfo Pointer to the {@link GamePerformance_PackageInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param appVersion The version of the app.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_PackageInfo_SetAppVersion(
        packageInfo: *mut GamePerformance_PackageInfo,
        appVersion: *const ::std::os::raw::c_char,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set engine type for {@link GamePerformance_PackageInfo} instance.\n\n @param packageInfo Pointer to the {@link GamePerformance_PackageInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param engineType The type of the engine {@link GamePerformance_EngineType}.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_PackageInfo_SetEngineType(
        packageInfo: *mut GamePerformance_PackageInfo,
        engineType: GamePerformance_EngineType,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set engine version for {@link GamePerformance_PackageInfo} instance.\n\n @param packageInfo Pointer to the {@link GamePerformance_PackageInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param engineVersion The version of the engine.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_PackageInfo_SetEngineVersion(
        packageInfo: *mut GamePerformance_PackageInfo,
        engineVersion: *const ::std::os::raw::c_char,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set game type for {@link GamePerformance_PackageInfo} instance.\n\n @param packageInfo Pointer to the {@link GamePerformance_PackageInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param gameType The type of the game {@link GamePerformance_GameType}.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_PackageInfo_SetGameType(
        packageInfo: *mut GamePerformance_PackageInfo,
        gameType: GamePerformance_GameType,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set whether vulkan is supported  for {@link GamePerformance_PackageInfo} instance.\n\n @param packageInfo Pointer to the {@link GamePerformance_PackageInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param vulkanSupported Whether vulkan is supported.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_PackageInfo_SetVulkanSupported(
        packageInfo: *mut GamePerformance_PackageInfo,
        vulkanSupported: bool,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Update game package info.\n\n @param packageInfo Pointer to the {@link GamePerformance_PackageInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n         {@link GAME_PERFORMANCE_INTERNAL_ERROR} 1010300001 - System internal error.\n         {@link GAME_PERFORMANCE_INVALID_REQUEST} 1010300003 - Invalid request.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_UpdatePackageInfo(
        packageInfo: *mut GamePerformance_PackageInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Create {@link GamePerformance_ConfigInfo} instance,\n which is used in {@link HMS_GamePerformance_UpdateConfigInfo}.\n\n @param configInfo Output data. {@link GamePerformance_ConfigInfo} instance.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_CreateConfigInfo(
        configInfo: *mut *mut GamePerformance_ConfigInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Destroy {@link GamePerformance_ConfigInfo} instance, When the instance is no longer needed.\n\n @param configInfo Secondary pointer to the {@link GamePerformance_ConfigInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_DestroyConfigInfo(
        configInfo: *mut *mut GamePerformance_ConfigInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set max picture quality level for {@link GamePerformance_ConfigInfo} instance.\n\n @param configInfo Pointer to the {@link GamePerformance_ConfigInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param maxPictureQualityLevel Max picture quality level.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_ConfigInfo_SetMaxPictureQualityLevel(
        configInfo: *mut GamePerformance_ConfigInfo,
        maxPictureQualityLevel: GamePerformance_PictureQualityLevel,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set current picture quality level for {@link GamePerformance_ConfigInfo} instance.\n\n @param configInfo Pointer to the {@link GamePerformance_ConfigInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param currentPictureQualityLevel Current picture quality level.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_ConfigInfo_SetCurrentPictureQualityLevel(
        configInfo: *mut GamePerformance_ConfigInfo,
        currentPictureQualityLevel: GamePerformance_PictureQualityLevel,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set max frame rate for {@link GamePerformance_ConfigInfo} instance.\n\n @param configInfo Pointer to the {@link GamePerformance_ConfigInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param maxFrameRate Max frame rate.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_ConfigInfo_SetMaxFrameRate(
        configInfo: *mut GamePerformance_ConfigInfo,
        maxFrameRate: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set current frame rate for {@link GamePerformance_ConfigInfo} instance.\n\n @param configInfo Pointer to the {@link GamePerformance_ConfigInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param currentFrameRate Current frame rate.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_ConfigInfo_SetCurrentFrameRate(
        configInfo: *mut GamePerformance_ConfigInfo,
        currentFrameRate: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set max resolution for {@link GamePerformance_ConfigInfo} instance.\n\n @param configInfo Pointer to the {@link GamePerformance_ConfigInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param maxResolution Max resolution.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_ConfigInfo_SetMaxResolution(
        configInfo: *mut GamePerformance_ConfigInfo,
        maxResolution: *const ::std::os::raw::c_char,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set current resolution for {@link GamePerformance_ConfigInfo} instance.\n\n @param configInfo Pointer to the {@link GamePerformance_ConfigInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param currentResolution Current resolution.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_ConfigInfo_SetCurrentResolution(
        configInfo: *mut GamePerformance_ConfigInfo,
        currentResolution: *const ::std::os::raw::c_char,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set whether antiAliasing is enabled for {@link GamePerformance_ConfigInfo} instance.\n\n @param configInfo Pointer to the {@link GamePerformance_ConfigInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param antiAliasingEnabled Whether antiAliasing is enabled.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_ConfigInfo_SetAntiAliasingEnabled(
        configInfo: *mut GamePerformance_ConfigInfo,
        antiAliasingEnabled: bool,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set whether shadow is enabled for {@link GamePerformance_ConfigInfo} instance.\n\n @param configInfo Pointer to the {@link GamePerformance_ConfigInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param shadowEnabled Whether shadow is enabled.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_ConfigInfo_SetShadowEnabled(
        configInfo: *mut GamePerformance_ConfigInfo,
        shadowEnabled: bool,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set whether multi thread is enabled for {@link GamePerformance_ConfigInfo} instance.\n\n @param configInfo Pointer to the {@link GamePerformance_ConfigInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param multithreadingEnabled Whether multi thread is enabled.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_ConfigInfo_SetMultithreadingEnabled(
        configInfo: *mut GamePerformance_ConfigInfo,
        multithreadingEnabled: bool,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set whether particle is enabled for {@link GamePerformance_ConfigInfo} instance.\n\n @param configInfo Pointer to the {@link GamePerformance_ConfigInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param particleEnabled Whether particle is enabled.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_ConfigInfo_SetParticleEnabled(
        configInfo: *mut GamePerformance_ConfigInfo,
        particleEnabled: bool,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set whether HD mode is enabled for {@link GamePerformance_ConfigInfo} instance.\n\n @param configInfo Pointer to the {@link GamePerformance_ConfigInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param hdModeEnabled Whether HD mode is enabled.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_ConfigInfo_SetHdModeEnabled(
        configInfo: *mut GamePerformance_ConfigInfo,
        hdModeEnabled: bool,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Update game config info.\n\n @param configInfo Pointer to the {@link GamePerformance_ConfigInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n         {@link GAME_PERFORMANCE_INTERNAL_ERROR} 1010300001 - System internal error.\n         {@link GAME_PERFORMANCE_INVALID_REQUEST} 1010300003 - Invalid request.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_UpdateConfigInfo(
        configInfo: *mut GamePerformance_ConfigInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Create {@link GamePerformance_SceneInfo} instance,\n which is used in {@link HMS_GamePerformance_UpdateSceneInfo}\n\n @param sceneInfo Output data. {@link GamePerformance_SceneInfo} instance.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_CreateSceneInfo(
        sceneInfo: *mut *mut GamePerformance_SceneInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Destroy {@link GamePerformance_SceneInfo} instance, When the instance is no longer needed.\n\n @param sceneInfo Secondary pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_DestroySceneInfo(
        sceneInfo: *mut *mut GamePerformance_SceneInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set scene ID for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param sceneID Scene ID.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetSceneID(
        sceneInfo: *mut GamePerformance_SceneInfo,
        sceneID: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set scene description for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param description Scene description.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetDescription(
        sceneInfo: *mut GamePerformance_SceneInfo,
        description: *const ::std::os::raw::c_char,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set sub scene ID for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param subSceneID Sub scene ID\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetSubSceneID(
        sceneInfo: *mut GamePerformance_SceneInfo,
        subSceneID: *const ::std::os::raw::c_char,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set sub scene description for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param subDescription Sub scene description.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetSubDescription(
        sceneInfo: *mut GamePerformance_SceneInfo,
        subDescription: *const ::std::os::raw::c_char,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set importance level of scene for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param importanceLevel Importance level of scene {@link GamePerformance_SceneImportanceLevel}\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetImportanceLevel(
        sceneInfo: *mut GamePerformance_SceneInfo,
        importanceLevel: GamePerformance_SceneImportanceLevel,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set scene frequency for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param sceneFrequency Scene frequency.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetSceneFrequency(
        sceneInfo: *mut GamePerformance_SceneInfo,
        sceneFrequency: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set length of time in the scene for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param sceneTime Length of time in the scene.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetSceneTime(
        sceneInfo: *mut GamePerformance_SceneInfo,
        sceneTime: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set recommended CPU level for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param recommendedCpuLevel Recommended CPU level {@link GamePerformance_CpuLevel}.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetRecommendedCpuLevel(
        sceneInfo: *mut GamePerformance_SceneInfo,
        recommendedCpuLevel: GamePerformance_CpuLevel,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set recommended GPU level for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param recommendedGpuLevel Recommended GPU level  {@link GamePerformance_GpuLevel}\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetRecommendedGpuLevel(
        sceneInfo: *mut GamePerformance_SceneInfo,
        recommendedGpuLevel: GamePerformance_GpuLevel,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set recommended DDR level for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param recommendedDdrLevel Recommended DDR level {@link GamePerformance_DdrLevel}.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetRecommendedDdrLevel(
        sceneInfo: *mut GamePerformance_SceneInfo,
        recommendedDdrLevel: GamePerformance_DdrLevel,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set max frame rate in the scene for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param maxFrameRate Max frame rate in the scene.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetMaxFrameRate(
        sceneInfo: *mut GamePerformance_SceneInfo,
        maxFrameRate: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set current frame rate in the scene for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param currentFrameRate Current frame rate in the scene.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetCurrentFrameRate(
        sceneInfo: *mut GamePerformance_SceneInfo,
        currentFrameRate: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set name of key thread for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param keyThread Name of key thread.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetKeyThread(
        sceneInfo: *mut GamePerformance_SceneInfo,
        keyThread: *const ::std::os::raw::c_char,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set drawCall count for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param drawCallCount DrawCall count.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetDrawCallCount(
        sceneInfo: *mut GamePerformance_SceneInfo,
        drawCallCount: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set vertex count for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param vertexCount Vertex count.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetVertexCount(
        sceneInfo: *mut GamePerformance_SceneInfo,
        vertexCount: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set triangle count for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param triangleCount Triangle count.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetTriangleCount(
        sceneInfo: *mut GamePerformance_SceneInfo,
        triangleCount: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set shader count for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param shaderCount Shader count.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetShaderCount(
        sceneInfo: *mut GamePerformance_SceneInfo,
        shaderCount: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set texture count for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param textureCount Texture count.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetTextureCount(
        sceneInfo: *mut GamePerformance_SceneInfo,
        textureCount: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set mesh count for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param meshCount Mesh count.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetMeshCount(
        sceneInfo: *mut GamePerformance_SceneInfo,
        meshCount: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set channel count for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param channelCount Channel count.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetChannelCount(
        sceneInfo: *mut GamePerformance_SceneInfo,
        channelCount: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set participant count for {@link GamePerformance_SceneInfo} instance.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param participantCount Participant count.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_SceneInfo_SetParticipantCount(
        sceneInfo: *mut GamePerformance_SceneInfo,
        participantCount: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Update game scene info.\n\n @param sceneInfo Pointer to the {@link GamePerformance_SceneInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n         {@link GAME_PERFORMANCE_INTERNAL_ERROR} 1010300001 - System internal error.\n         {@link GAME_PERFORMANCE_INVALID_REQUEST} 1010300003 - Invalid request.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_UpdateSceneInfo(
        sceneInfo: *mut GamePerformance_SceneInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Create {@link GamePerformance_NetInfo} instance,\n which is used in {@link HMS_GamePerformance_UpdateNetInfo}.\n\n @param netInfo Output data. {@link GamePerformance_NetInfo} instance.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_CreateNetInfo(
        netInfo: *mut *mut GamePerformance_NetInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Destroy {@link GamePerformance_NetInfo} instance, When the instance is no longer needed.\n\n @param netInfo Secondary pointer to the {@link GamePerformance_NetInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_DestroyNetInfo(
        netInfo: *mut *mut GamePerformance_NetInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set total net latency for {@link GamePerformance_NetInfo} instance.\n\n @param netInfo Pointer to the {@link GamePerformance_NetInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param total Total net latency.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_NetInfo_SetTotalLatency(
        netInfo: *mut GamePerformance_NetInfo,
        total: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set up net latency for {@link GamePerformance_NetInfo} instance.\n\n @param netInfo Pointer to the {@link GamePerformance_NetInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param up Up net latency.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_NetInfo_SetUplinkLatency(
        netInfo: *mut GamePerformance_NetInfo,
        up: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set down net latency for {@link GamePerformance_NetInfo} instance.\n\n @param netInfo Pointer to the {@link GamePerformance_NetInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param down Down net latency.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_NetInfo_SetDownlinkLatency(
        netInfo: *mut GamePerformance_NetInfo,
        down: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set server net latency for {@link GamePerformance_NetInfo} instance.\n\n @param netInfo Pointer to the {@link GamePerformance_NetInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param server Server net latency.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_NetInfo_SetServerLatency(
        netInfo: *mut GamePerformance_NetInfo,
        server: i64,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set net load for {@link GamePerformance_NetInfo} instance.\n\n @param netInfo Pointer to the {@link GamePerformance_NetInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param netLoad Net load {@link GamePerformance_NetLoad}.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_NetInfo_SetNetLoad(
        netInfo: *mut GamePerformance_NetInfo,
        netLoad: GamePerformance_NetLoad,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Update game net info.\n\n @param netInfo Pointer to the {@link GamePerformance_NetInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n         {@link GAME_PERFORMANCE_INTERNAL_ERROR} 1010300001 - System internal error.\n         {@link GAME_PERFORMANCE_INVALID_REQUEST} 1010300003 - Invalid request.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_UpdateNetInfo(
        netInfo: *mut GamePerformance_NetInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Create {@link GamePerformance_PlayerInfo} instance,\n which is used in {@link HMS_GamePerformance_UpdatePlayerInfo}.\n\n @param playerInfo Output data. {@link GamePerformance_PlayerInfo} instance.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_CreatePlayerInfo(
        playerInfo: *mut *mut GamePerformance_PlayerInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Destroy {@link GamePerformance_PlayerInfo} instance, When the instance is no longer needed.\n\n @param playerInfo Secondary pointer to the {@link GamePerformance_PlayerInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_DestroyPlayerInfo(
        playerInfo: *mut *mut GamePerformance_PlayerInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set gamePlayerId for {@link GamePerformance_PlayerInfo} instance.\n\n @param playerInfo Pointer to the {@link GamePerformance_PlayerInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param gamePlayerId GamePlayerId.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_PlayerInfo_SetGamePlayerId(
        playerInfo: *mut GamePerformance_PlayerInfo,
        gamePlayerId: *const ::std::os::raw::c_char,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set teamPlayerId for {@link GamePerformance_PlayerInfo} instance.\n\n @param playerInfo Pointer to the {@link GamePerformance_PlayerInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param teamPlayerId TeamPlayerId.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_PlayerInfo_SetTeamPlayerId(
        playerInfo: *mut GamePerformance_PlayerInfo,
        teamPlayerId: *const ::std::os::raw::c_char,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set thirdOpenId for {@link GamePerformance_PlayerInfo} instance.\n\n @param playerInfo Pointer to the {@link GamePerformance_PlayerInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param thirdOpenId ThirdOpenId.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_PlayerInfo_SetThirdOpenId(
        playerInfo: *mut GamePerformance_PlayerInfo,
        thirdOpenId: *const ::std::os::raw::c_char,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Update game player info.\n\n @param playerInfo Pointer to the {@link GamePerformance_PlayerInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n         {@link GAME_PERFORMANCE_INTERNAL_ERROR} 1010300001 - System internal error.\n         {@link GAME_PERFORMANCE_INVALID_REQUEST} 1010300003 - Invalid request.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_UpdatePlayerInfo(
        playerInfo: *mut GamePerformance_PlayerInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Subscribes thermal level change event. When target word is detected, the callback is invoked.\n\n the callback will be invoked once when thermal level changed and thermal level is less than 3.\n the callback will be invoked once evenry ten seconds when thermal level is greater than or equal level 3.\n\n @param types Types of device information that register callback for.\n @param size Size of types.\n @param callback Call back function {@link GamePerformance_ThermalLevelChangedCallback}.\n @param userData User specific data.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n         {@link GAME_PERFORMANCE_INTERNAL_ERROR} 1010300001 - System internal error.\n         {@link GAME_PERFORMANCE_INVALID_REQUEST} 1010300003 - Invalid request.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_RegisterThermalLevelChangedCallback(
        types: *mut *mut GamePerformance_DeviceInfoType,
        size: usize,
        callback: GamePerformance_ThermalLevelChangedCallback,
        userData: *mut ::std::os::raw::c_void,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Unsubscribes thermal level change event for the callback.\n\n @param callback Call back function {@link GamePerformance_ThermalLevelChangedCallback}.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n         {@link GAME_PERFORMANCE_INTERNAL_ERROR} 1010300001 - System internal error.\n         {@link GAME_PERFORMANCE_INVALID_REQUEST} 1010300003 - Invalid request.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_UnregisterThermalLevelChangedCallback(
        callback: GamePerformance_ThermalLevelChangedCallback,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Unsubscribes thermal level change event for all of callbacks.\n\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_INTERNAL_ERROR} 1010300001 - System internal error.\n         {@link GAME_PERFORMANCE_INVALID_REQUEST} 1010300003 - Invalid request.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_UnregisterAllThermalLevelChangedCallbacks(
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Create {@link GamePerformance_ThermalInfoQueryParameters} instance ,\n which is used in {@link HMS_GamePerformance_QueryThermalInfo}.\n\n @param parameters Output data. {@link GamePerformance_ThermalInfoQueryParameters} instance.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_CreateThermalInfoQueryParameters(
        parameters: *mut *mut GamePerformance_ThermalInfoQueryParameters,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Destroy {@link GamePerformance_ThermalInfoQueryParameters} instance, When the instance is no longer needed.\n\n @param parameters Secondary pointer to the {@link GamePerformance_ThermalInfoQueryParameters} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_DestroyThermalInfoQueryParameters(
        parameters: *mut *mut GamePerformance_ThermalInfoQueryParameters,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set needsPrediction for {@link GamePerformance_ThermalInfoQueryParameters} instance.\n\n @param parameters Pointer to the {@link GamePerformance_ThermalInfoQueryParameters} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param needsPrediction If need predict thermal trend, thermalMargin and thermalTrend will be answered.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_ThermalInfoQueryParameters_SetNeedsPrediction(
        parameters: *mut GamePerformance_ThermalInfoQueryParameters,
        needsPrediction: bool,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Set target thermal level of thermal predict for {@link GamePerformance_ThermalInfoQueryParameters} instance.\n\n @param parameters Pointer to the {@link GamePerformance_ThermalInfoQueryParameters} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param targetThermalLevel Target thermal level of thermal predict. If need predict thermal trend,\n thermalMargin and thermalTrend will be answered according to the targetThermalLevel.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_ThermalInfoQueryParameters_SetTargetThermalLevel(
        parameters: *mut GamePerformance_ThermalInfoQueryParameters,
        targetThermalLevel: i32,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Query thermal info.\n\n @param parameters Pointer to the {@link GamePerformance_ThermalInfoQueryParameters} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param thermalInfo Output data. {@link GamePerformance_ThermalInfo} instance.\n When the thermal info is no longer needed, it must be released using {@link HMS_GamePerformance_DestroyThermalInfo}.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n         {@link GAME_PERFORMANCE_INTERNAL_ERROR} 1010300001 - System internal error.\n         {@link GAME_PERFORMANCE_INVALID_REQUEST} 1010300003 - Invalid request.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_QueryThermalInfo(
        parameters: *mut GamePerformance_ThermalInfoQueryParameters,
        thermalInfo: *mut *mut GamePerformance_ThermalInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Destroy {@link GamePerformance_ThermalInfo} instance, When the instance is no longer needed.\n\n @param thermalInfo Secondary pointer to the {@link GamePerformance_ThermalInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_DestroyThermalInfo(
        thermalInfo: *mut *mut GamePerformance_ThermalInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Query GPU info.\n\n @param gpuInfo Output data. {@link GamePerformance_GpuInfo} instance.\n When the GPU info is no longer needed, it must be released using {@link HMS_GamePerformance_DestroyGpuInfo}.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n         {@link GAME_PERFORMANCE_INTERNAL_ERROR} 1010300001 - System internal error.\n         {@link GAME_PERFORMANCE_INVALID_REQUEST} 1010300003 - Invalid request.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_QueryGpuInfo(
        gpuInfo: *mut *mut GamePerformance_GpuInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Destroy {@link GamePerformance_GpuInfo} instance, When the instance is no longer needed.\n\n @param gpuInfo Secondary pointer to the {@link GamePerformance_GpuInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_DestroyGpuInfo(
        gpuInfo: *mut *mut GamePerformance_GpuInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Get GPU info {@link GamePerformance_GpuInfo} from device info {@link GamePerformance_DeviceInfo}.\n\n @param deviceInfo Pointer to the {@link GamePerformance_DeviceInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param gpuInfo Output data. Secondary pointer to the {@link GamePerformance_GpuInfo} instance.\n When the GPU info is no longer needed, it must be released using {@link HMS_GamePerformance_DestroyGpuInfo}.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_DeviceInfo_GetGpuInfo(
        deviceInfo: *mut GamePerformance_DeviceInfo,
        gpuInfo: *mut *mut GamePerformance_GpuInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Get thermal info {@link GamePerformance_ThermalInfo} from device info {@link GamePerformance_DeviceInfo}.\n\n @param deviceInfo Pointer to the {@link GamePerformance_DeviceInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param thermalInfo Output data. Secondary pointer to the {@link GamePerformance_ThermalInfo} instance.\n When the thermal info is no longer needed, it must be released using {@link HMS_GamePerformance_DestroyThermalInfo}.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_DeviceInfo_GetThermalInfo(
        deviceInfo: *mut GamePerformance_DeviceInfo,
        thermalInfo: *mut *mut GamePerformance_ThermalInfo,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Get thermal margin from thermal info {@link GamePerformance_ThermalInfo}.\n\n @param thermalInfo Pointer to the {@link GamePerformance_ThermalInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param thermalMargin Output data. Thermal margin.\n provides an estimate of the thermal margin the device will have before it reaches the threshold.\n A negative value indicates that the system cannot predict thermal margin.\n Unit: second.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_ThermalInfo_GetThermalMargin(
        thermalInfo: *mut GamePerformance_ThermalInfo,
        thermalMargin: *mut i32,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Get thermal trend from thermal info {@link GamePerformance_ThermalInfo}.\n\n @param thermalInfo Pointer to the {@link GamePerformance_ThermalInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param thermalTrend Output data. Thermal trend.\n Thermal trend, rate of current temperature rise. The value ranges from -100 to 100.\n A negative value indicates that the temperature is decreasing.\n The absolute value of the magnitude represents the rate of rise or fall.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_ThermalInfo_GetThermalTrend(
        thermalInfo: *mut GamePerformance_ThermalInfo,
        thermalTrend: *mut i32,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Get thermal level from thermal info {@link GamePerformance_ThermalInfo}.\n\n @param thermalInfo Pointer to the {@link GamePerformance_ThermalInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param thermalLevel Output data. Temperature level.\n Temperature level. A higher value indicates a higher temperature.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_ThermalInfo_GetThermalLevel(
        thermalInfo: *mut GamePerformance_ThermalInfo,
        thermalLevel: *mut i32,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Get GPU load level from GPU info {@link GamePerformance_GpuInfo}.\n\n @param gpuInfo Pointer to the {@link GamePerformance_GpuInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param gpuLoadLevel Output data.  GPU laod level, the value ranges from 1 to 10 in ascending order.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_GpuInfo_GetGpuLoadLevel(
        gpuInfo: *mut GamePerformance_GpuInfo,
        gpuLoadLevel: *mut i32,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Get vertex load level from GPU info {@link GamePerformance_GpuInfo}.\n\n @param gpuInfo Pointer to the {@link GamePerformance_GpuInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param vertexLoadLevel Output data. GPU vertex level, the value ranges from 1 to 10 in ascending order.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_GpuInfo_GetVertexLoadLevel(
        gpuInfo: *mut GamePerformance_GpuInfo,
        vertexLoadLevel: *mut i32,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Get fragment load level from GPU info {@link GamePerformance_GpuInfo}.\n\n @param gpuInfo Pointer to the {@link GamePerformance_GpuInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param fragmentLoadLevel Output data. GPU fragment load level, the value ranges from 1 to 10 in ascending order.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_GpuInfo_GetFragmentLoadLevel(
        gpuInfo: *mut GamePerformance_GpuInfo,
        fragmentLoadLevel: *mut i32,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Get texture load level from GPU info {@link GamePerformance_GpuInfo}.\n\n @param gpuInfo Pointer to the {@link GamePerformance_GpuInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param textureLoadLevel Output data. GPU texture load level, the value ranges from 1 to 10 in ascending order.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_GpuInfo_GetTextureLoadLevel(
        gpuInfo: *mut GamePerformance_GpuInfo,
        textureLoadLevel: *mut i32,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Get bindwith load level from GPU info {@link GamePerformance_GpuInfo}.\n\n @param gpuInfo Pointer to the {@link GamePerformance_GpuInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param bandwidthLoadLevel Output data. GPU bindwith load level, the value ranges from 1 to 10 in ascending order.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_GpuInfo_GetBandwidthLoadLevel(
        gpuInfo: *mut GamePerformance_GpuInfo,
        bandwidthLoadLevel: *mut i32,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Get current GPU current frequency from GPU info {@link GamePerformance_GpuInfo}.\n\n @param gpuInfo Pointer to the {@link GamePerformance_GpuInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @param currentFrequency Output data. current GPU current frequency,\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_GpuInfo_GetCurrentFrequency(
        gpuInfo: *mut GamePerformance_GpuInfo,
        currentFrequency: *mut i32,
    ) -> GamePerformance_ErrorCode;
}
unsafe extern "C" {
    #[doc = " @brief Destroy {@link GamePerformance_DeviceInfo} instance, When the instance is no longer needed.\n\n @param deviceInfo Secondary pointer to the {@link GamePerformance_DeviceInfo} instance.\n The value can not be null. Otherwise, an error code will be returned.\n @return Returns the status code of the exception.\n         {@link GAME_PERFORMANCE_SUCCESS} 0 - Success.\n         {@link GAME_PERFORMANCE_PARAM_INVALID} 401 - Invalid parameter.\n @since 5.0.2(14)"]
    pub fn HMS_GamePerformance_DestroyDeviceInfo(
        deviceInfo: *mut *mut GamePerformance_DeviceInfo,
    ) -> GamePerformance_ErrorCode;
}
